apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: game-service-green-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: game-service
      version: green
  namespaceSelector:
    matchNames:
      - game
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
