kind: ServiceMonitor
metadata:
  name: game-service-blue-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: game-service
      version: blue
  namespaceSelector:
    matchNames:
      - game
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
