apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: game
spec:
  selector:
    app: game-service
    version: blue # Default, will be patched during deployment
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
