{
 "title": "EKS-MULTI-SERVICE-DEPLOY",
 "time": { "from": "2025-07-26T06:29:18.042Z", "to": "2025-07-26T06:34:18.042Z" },
 "panels": [
  {
   "title": "Order Service - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    namespace=\"order\", \r\n    pod=~\"order-service.*\", \r\n    container!=\"POD\"\r\n  }[2m])\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Analytics Service - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (\r\n  rate(container_cpu_usage_seconds_total{namespace=\"analytics\", pod=~\"analytics-service-.*\", container!=\"POD\"}[2m])\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Game Service - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    namespace=\"game\", \r\n    pod=~\"game-service-.*\", \r\n    container!=\"POD\"\r\n  }[2m])\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Service - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"order\", pod=~\"order-service-.*\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Analytics Service - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"analytics\", pod=~\"analytics-service-.*\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Game Service - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"game\", pod=~\"game-service-.*\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}