{
 "title": "Game Service Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage (RSS)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Memory (bytes)" }
   ]
  },
  {
   "title": "CPU Time (User)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[1m])",
     "legendFormat": "CPU time"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "Event Loop Lag" }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "stat",
   "gridPos": { "x": 6, "y": 4, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nodejs_heap_used_bytes", "legendFormat": "Heap Used" }
   ]
  }
 ]
}