name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: shalini1772/game-service
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

    - name: Push image to Docker Hub
      run: docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f k8s/mysql-deployment.yaml
        kubectl apply -f k8s/game-service-deployment.yaml

    - name: Wait for rollout
      run: |
        kubectl rollout status deployment/game-service

    - name: Run integration test
      run: |
        POD=$(kubectl get pods -l app=game-service -o jsonpath="{.items[0].metadata.name}")
        kubectl exec $POD -- curl -s http://localhost:3000/health || echo "Health check failed"
