name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: shalini1772/game-service
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/mysql-deployment.yaml
          kubectl apply -f k8s/game-service-deployment.yaml

      - name: Wait for Deployment Rollout
        run: |
          kubectl rollout status deployment/game-service

      - name: Run Health Check
        run: |
          POD=$(kubectl get pods -l app=game-service -o jsonpath="{.items[0].metadata.name}")
          STATUS=$(kubectl exec $POD -- curl -s http://localhost:3000/health || echo "fail")
          echo "Health Check Status: $STATUS"
          if [[ "$STATUS" != *"OK"* && "$STATUS" != *"healthy"* ]]; then
            echo "❌ Health check failed"
            exit 1
          else
            echo "✅ Health check passed"
          fi
