apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
  namespace: static
  labels:
    app: static-site
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
        - name: static-site
          image: shalini1772/static-site:${IMAGE_TAG}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-site
  namespace: static
spec:
  selector:
    app: static-site
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
