apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: analytics-service-blue
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: analytics-service
      version: blue
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - analytics
