kind: ServiceMonitor
metadata:
  name: analytics-service-green-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: analytics-service
      version: green
  namespaceSelector:
    matchNames:
      - analytics
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
