name: CI/CD for Microservices

on:
  push:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      game: ${{ steps.filter.outputs.game }}
      analytics: ${{ steps.filter.outputs.analytics }}
      order: ${{ steps.filter.outputs.order }}
    steps:
      - uses: actions/checkout@v3

      - name: Detect which service changed
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            game:
              - 'game-service/**'
            analytics:
              - 'analytics-service/**'
            order:
              - 'order-service/**'

  deploy-game:
    needs: detect-changes
    if: needs.detect-changes.outputs.game == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build, tag, and push game-service
        run: |
          docker build -t game-service ./game-service
          docker tag game-service shalini1772/game-service:0.1
          docker push shalini1772/game-service:0.1

      - name: Set up AWS credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region "${{ secrets.AWS_REGION }}"

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy to EKS - game-service
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl create namespace game --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f game-service/k8s/game-service-deployment.yaml -n game
          kubectl apply -f game-service/k8s/mysql-deployment.yaml -n game
          kubectl apply -f game-service/k8s/game-ingress.yaml -n game

  deploy-analytics:
    needs: detect-changes
    if: needs.detect-changes.outputs.analytics == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build, tag, and push analytics-service
        run: |
          docker build -t analytics-service ./analytics-service
          docker tag analytics-service shalini1772/analytics-service:0.1
          docker push shalini1772/analytics-service:0.1

      - name: Set up AWS credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region "${{ secrets.AWS_REGION }}"

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy to EKS - analytics-service
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl create namespace analytics --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f analytics-service/k8s/analytics-service-deployment.yaml -n analytics
          kubectl apply -f analytics-service/k8s/analytics-ingress.yaml -n analytics

  deploy-order:
    needs: detect-changes
    if: needs.detect-changes.outputs.order == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build, tag, and push order-service
        run: |
          docker build -t order-service ./order-service
          docker tag order-service shalini1772/order-service:0.1
          docker push shalini1772/order-service:0.1

      - name: Set up AWS credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region "${{ secrets.AWS_REGION }}"

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy to EKS - order-service
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl create namespace order --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f order-service/k8s/order-service-deployment.yaml -n order
          kubectl apply -f order-service/k8s/mysql-deployment.yaml -n order
          kubectl apply -f order-service/k8s/order-ingress.yaml -n order
